export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    SIGN_UP_REQUEST: 'SIGNUP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
}

export const employeeConstants ={
    GET_ALL_REQUEST :"GET_ALL_REQUEST",
    GET_ALL_SUCCESS : "GET_ALL_SUCCESS",
    GET_ALL_FAILURE : "GET_ALL_FAILURE",
    UPDATE_REQUEST: "UPDATE_REQUEST",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    UPDATE_FAILURE: "UPDATE_FAILURE",
    DELETE_REQUEST :"DELETE_REQUEST",
    DELETE_SUCCESS : "DELETE_SUCCESS",
    DELETE_FAILURE : "DELETE_FAILURE",
    ADD_REQUEST :"ADD_REQUEST",
    ADD_SUCCESS : "ADD_SUCCESS",
    ADD_FAILURE : "ADD_FAILURE",
}
